name: "🚀 publish nuget"

on:
  release:
    types: [published]

jobs:
  build:
    name: build and copy npm
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install
        run: cd npm && npm ci
      - name: build js bundle
        run: cd npm && npm run build
      - name: copy js bundle
        run: cd npm/build/ && cp sgGeocode_bundle ../../nuget/SmartyStreetsGoogleGeocode

  release:
    name: test and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: build js bundle
        run: cd npm && npm run build
      - name: copy js bundle
        run: cd npm/build/ && cp sgGeocode_bundle ../../nuget/SmartyStreetsGoogleGeocode
      - name: Build solution
        run: |
          cd nuget/SmartyStreetsGoogleGeocode
          dotnet build --configuration release
      - name: Test
        run: |
          cd nuget/SmartyStreetsGoogleGeocode
          dotnet test
      - name: Create NuGet package
        run: |
          cd nuget/SmartyStreetsGoogleGeocode
          dotnet pack -c Release /p:Version=${{ github.event.release.tag_name }}
      - name: Push with dotnet
        run: |
          cd nuget/SmartyStreetsGoogleGeocode
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
