name: "🚀 test npm"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: test npm
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Install
        run: cd npm && npm ci
      - name: tests
        run: cd npm && npx jest
        env:
          CI: true
          WEB_KEY: ${{ secrets.WEB_KEY }}
